Publish release 2024.05
OpenVisualCloud/Video-Super-Resolution-Library.Enhanced-BasicVSR pull request #11
Opened 2024-11-11 02:55 UTC by linxie47

2024-11-12 01:43 UTC, xiaoxial requested changes
LGTM

2024-11-12 01:43 UTC, xiaoxial approved these changes

2024-11-12 01:57 UTC, djie1 reviewed
@wangjingz is it proper to put this file "ivsr_sdk/license/Eval_License_Agreement_for_Enhanced_VSR.pdf"?

2024-11-12 02:28 UTC, wangjingz approved these changes

2024-11-13 02:31 UTC, djie1 approved these changes
LGTM

2024-11-13 07:32 UTC, merged